#!/bin/bash

# Deployment of Jekyll-Sites  
# via Git Bare Repository and post-receive hook.
#
# See https://netzaffe.de/jekyll-deployment-via-bare-repository-und-post-receive-hook.html
# for requirements and more detailed description (german)
# set -x

# Get pushed branch

read oldrev newrev ref 
pushed_branch=${ref#refs/heads/} 

## Source configuration from repository

config=$(mktemp)
git-show HEAD:deploy.conf > $config || exit 
source $config

## Do the magic

[ "$pushed_branch" != "$build_branch" ] && exit 1
tmp=$(mktemp -d)
git clone $git_repo $tmp
cd $tmp
bundle install || bundle install --redownload
bundle exec jekyll build --source $tmp --destination $www
rm -rf $tmp $config
