#!/usr/bin/env bash

# Deployment of Jekyll-Sites via Git Bare Repository and post-receive hook.
# https://github.com/fl3a/jekyll_deployment
#
# USAGE:
# - git hook: Place this script as .hooks/post-receive within your git repository
# - standalone: ${SCRIPT} /path/to/git-bare-repository
#
set -x

if [ -z "$1" ]; then
  read oldrev newrev ref 
  pushed_branch=${ref#refs/heads/} 
elif [ -d "$1" ] && { cd $1 ; git rev-parse --is-bare-repository ; } >/dev/null; then
  pushed_branch=""
else
  exit
fi

config=$(mktemp)
git show HEAD:deploy.conf > $config || exit 
source $config

[ -z "$pushed_branch" ] && pushed_branch=$build_branch
[ "$pushed_branch" != "$build_branch" ] && exit 
[ -f "$extra_vars" ] && source $extra_vars

tmp=$(mktemp -d)
git clone --single-branch --branch $build_branch $git_repo $tmp
cd $tmp
bundle install || bundle install --redownload
JEKYLL_ENV=${env:-production} \
  JEKYLL_BUILD_REVISION=$rev \
  JEKYLL_GITHUB_TOKEN=$JEKYLL_GITHUB_TOKEN \
  bundle exec jekyll build --source $tmp --destination $www $build_suffix
rm -rf $tmp $config
$post_exec
